# Generated by Django 3.0.4 on 2021-05-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField()),
                ('reciever', models.TextField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
